# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_world": "00_core.ipynb",
         "Ability": "00_core.ipynb",
         "Character": "00_core.ipynb",
         "Mage": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://pmaxit.github.io/tfbook_pages/"

git_url = "https://github.com/pmaxit/tfbook_pages/tree/master/"

def custom_doc_links(name): return None
